<?php

namespace App\Exports;

use App\Models\InvestmentContractDocuments;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class InvestmentContractsExport implements FromCollection, WithHeadings
{
    /**
     */

    protected $search;
    protected $filters;

    public function __construct($search = null, array $filters = [])
    {
        $this->search = $search;
        $this->filters = $filters;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    public function collection()
    {
        $permittedCompanyIds = getUserPermittedCompanyIds(auth()->user()->id, 'investment');

        //
        $query = InvestmentContractDocuments::with('investor', 'generatedBy', 'investment', 'company', 'agreementType', 'agreementTemplate');

        $query->whereHas('company', function ($q) use ($permittedCompanyIds) {
            $q->whereIn('company_id', $permittedCompanyIds);
        });

        if (!empty($filters['investor_id'])) {
            $query->where('investor_id', $filters['investor_id']);
        }
        // dd($result);

        if (!empty($filters['search'])) {
            $query
                // ->orWhere('investment_amount', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('investment_date', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('investment_code', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('maturity_date', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('profit_perc', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('received_amount', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('profit_release_date', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('nominee_name', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('nominee_email', 'like', '%' . $filters['search'] . '%')
                // ->orWhere('nominee_phone', 'like', '%' . $filters['search'] . '%')
                ->WhereHas('investor', function ($q) use ($filters) {
                    $q->where('investor_name', 'like', '%' . $filters['search'] . '%');
                })
                // ->orWhereHas('investment', function ($q) use ($filters) {
                //     $q->where('investment_code', 'like', '%' . $filters['search'] . '%');
                // })

                ->orWhereHas('agreementType', function ($q) use ($filters) {
                    $q->where('investor_agreement_type', 'like', '%' . $filters['search'] . '%');
                })
                ->orWhereHas('agreementTemplate', function ($q) use ($filters) {
                    $q->whereRaw("CONCAT('V', version_no) LIKE ?", ['%' . $filters['search'] . '%']);
                })
                ->orWhereHas('company', function ($q) use ($filters) {
                    $q->where('company_name', 'like', '%' . $filters['search'] . '%');
                })
                ->orWhereRaw("CAST(investment_contract_documents.id AS CHAR) LIKE ?", ['%' . $filters['search'] . '%']);
        }
        $results = $query->get();

        return $results->map(function ($row) {
            return [
                'ID' => $row->id,
                'Company Name' => $row->company->company_name ?? '-',
                'Investor Name' => $row->investor ? $row->investor->investor_name . ' - ' . $row->investor->investor_code . ')' : '-',
                // 'Status' => $row->investor->investor_email ?? '-',
                'Contract Type' => $row->agreementType->investor_agreement_type ?? '-',
                'Version' => 'V' . $row->agreementTemplate->version_no ?? '-',
                'Generated By' => $row->generatedBy
                    ? $row->generatedBy->first_name . ' ' . $row->generatedBy->last_name
                    : '-',
                'Generated Date' => $row->generated_date
                    ? \Carbon\Carbon::parse($row->generated_date)->format('d M Y h:i A')
                    : '-',


            ];
        });
    }
    public function headings(): array
    {
        return [
            'ID',
            'Company Name',
            'Investor Name',
            // 'Status',
            'Contract Type',
            'Version',
            'Generated Date',
            'Generated By',
        ];
    }
}
